DROP TABLE PERSONAS CASCADE CONSTRAINTS;
DROP TABLE EVENTOS CASCADE CONSTRAINTS;
DROP TABLE OFERTAS_EVENTO CASCADE CONSTRAINTS;
DROP TABLE OFERTAS_VIVIENDA CASCADE CONSTRAINTS;
DROP TABLE OPERADORES_HOSTAL CASCADE CONSTRAINTS;
DROP TABLE OPERADORES_HOTEL CASCADE CONSTRAINTS;
DROP TABLE OPERADORES_VIVIENDA CASCADE CONSTRAINTS;
DROP TABLE SERVICIOS CASCADE CONSTRAINTS;
DROP TABLE OFERTAS_HOSTAL CASCADE CONSTRAINTS;
DROP TABLE OFERTAS_HOTEL CASCADE CONSTRAINTS;
DROP TABLE OFERTAS_APARTAMENTO CASCADE CONSTRAINTS;
DROP TABLE OFERTAS_PERSONANATURAL CASCADE CONSTRAINTS;
DROP TABLE OPERADORES_PERSONANATURAL CASCADE CONSTRAINTS;
DROP TABLE RESERVAS CASCADE CONSTRAINTS;
DROP TABLE GUSTAN CASCADE CONSTRAINTS;
DROP TABLE OFERTAS

CREATE TABLE PERSONAS (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR(255),
    CORREO VARCHAR(255),
    AFILIACION VARCHAR(255),
    CONSTRAINT CHECK_AFILIACION
        CHECK (AFILIACION IN ('estudiante', 'egresado', 'padre', 'profesor', 'empleado'))
);
CREATE TABLE OPERADORES_HOTEL (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    Direccion VARCHAR(255)
);
CREATE TABLE OPERADORES_HOSTAL (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL, 
    HORA_APERTURA VARCHAR(255) NOT NULL,
    HORA_CIERRE VARCHAR(255) NOT NULL
);
CREATE TABLE OPERADORES_PERSONANATURAL(
    ID NUMBER PRIMARY KEY,
    COSTO_SERVICIOS NUMBER NOT NULL,
    PERSONA NUMBER NOT NULL,
    CONSTRAINT FK_PERSONANATURAL_PERSONAS FOREIGN KEY (PERSONA)
    REFERENCES PERSONAS(ID)
);
CREATE TABLE EVENTOS(
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR(255),
    FECHA_INICIO DATE,
    FECHA_FINAL DATE
);
CREATE TABLE OPERADORES_VIVIENDA(
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR(255), 
    UBICACION VARCHAR(255)
);
CREATE TABLE OFERTAS_HOTEL(
    ID NUMBER PRIMARY KEY,
    TIPO_HABITACION VARCHAR(255) NOT NULL,
    PRECIO NUMBER NOT NULL,
    HOTEL NUMBER NOT NULL,
    ESTADO VARCHAR(255),
    CHECK (ESTADO IN ('habilitado', 'deshabilitado')),
    CONSTRAINT FK_OFERTA_HOTEL FOREIGN KEY (HOTEL)
    REFERENCES OPERADORES_HOTEL(ID),
    CONSTRAINT CHECK_TIPO_HABITACION
        CHECK (TIPO_HABITACION IN ('suite', 'semisuite', 'estandar'))
);
CREATE TABLE OFERTAS_HOSTAL(
    ID NUMBER PRIMARY KEY,
    PRECIO NUMBER NOT NULL,
    HOSTAL NUMBER NOT NULL,
    ESTADO VARCHAR(255),
    CHECK (ESTADO IN ('habilitado', 'deshabilitado')),
    CONSTRAINT FK_OFERTA_HOSTAL FOREIGN KEY (HOSTAL)
        REFERENCES OPERADORES_HOSTAL(ID)
);
CREATE TABLE OFERTAS_PERSONANATURAL(
    ID NUMBER PRIMARY KEY,
    PRECIO_MENSUAL NUMBER,
    PRECIO_SEMESTRE NUMBER,
    PERSONA_NATURAL NUMBER NOT NULL,
    CONSTRAINT FK_PERSNANATURAL_PN FOREIGN KEY (PERSONA_NATURAL)
        REFERENCES OPERADORES_PERSONANATURAL (ID)
);
CREATE TABLE OFERTAS_EVENTO(
    ID NUMBER PRIMARY KEY,
    PRECIO NUMBER NOT NULL,
    NUM_HABITACIONES NUMBER NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    MENAJE VARCHAR(255) NOT NULL,
    EVENTO NUMBER NOT NULL,
    CONSTRAINT FK_OFERTA_EVENTO FOREIGN KEY (EVENTO)
        REFERENCES EVENTOS(ID)
);
CREATE TABLE OFERTAS_VIVIENDA(
    ID NUMBER PRIMARY KEY,
    COSTO_NOCHE NUMBER NOT NULL,
    COSTO_MENSUAL NUMBER NOT NULL,
    COSTO_SEMESTRE NUMBER NOT NULL,
    MENAJE VARCHAR(255),
    CAPACIDAD NUMBER NOT NULL,
    VIVIENDA NUMBER NOT NULL,
    CONSTRAINT FK_OFERTAS_VIVIENDA FOREIGN KEY (VIVIENDA)
        REFERENCES OPERADORES_VIVIENDA(ID)
);
CREATE TABLE OFERTAS_APARTAMENTO(
    ID NUMBER PRIMARY KEY,
    COSTO NUMBER NOT NULL,
    SERVICIOS VARCHAR(255),
    INTERNET_TV VARCHAR(255),
    ADMINISTRACION VARCHAR(255),
    PERSONA NUMBER NOT NULL,
     CONSTRAINT FK_OFERTAAPTO_PERSONA FOREIGN KEY (PERSONA)
        REFERENCES PERSONAS(ID)
);
CREATE TABLE SERVICIOS(
    ID NUMBER PRIMARY KEY,
    ID_OFERTA NUMBER,
    NOM_SERVICIO VARCHAR(255) NOT NULL 
);
CREATE TABLE RESERVAS(
    ID NUMBER PRIMARY KEY,
    ID_OFERTA NUMBER NOT NULL,
    FECHA_RESERVA DATE NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    FECHA_OPORTUNA DATE,
    COSTO_CALCULADO NUMBER,
    ESTADO VARCHAR(255) NOT NULL,
    PERSONA NUMBER NOT NULL,
    CONSTRAINT FK_RESERVA_PERSONA FOREIGN KEY (PERSONA)
        REFERENCES PERSONAS(ID),
    CONSTRAINT CHECK_ESTADO
        CHECK (ESTADO IN ('activa', 'cancelada'))
);

CREATE TABLE GUSTAN(
PERSONA NUMBER NOT NULL,
SERVICIO VARCHAR(255) NOT NULL,
CONSTRAINT FK_QUIEREN_PERSONA FOREIGN KEY (PERSONA)
    REFERENCES PERSONAS(ID)
);

CREATE TABLE OFERTAS(
ID_OFERTA NUMBER NOT NULL,
TIPO_OFERTA VARCHAR(255) NOT NULL,
ID_OPERADOR NUMBER NOT NULL
);
